### ISSUE TITLE
Biopython DeprecationWarning for ungap() Method

### ISSUE THREAD

**Issue by monserrj** [widdowquinn/ncfp#45]
#### Summary:
BiopythonDeprecationWarning for the`ungap()` method, advising replacement with `replace()`.

#### Description:
The code is currently using the deprecated `ungap()` method in Biopython, which triggers a BiopythonDeprecationWarning. The warning suggests replacing `myseq.ungap(gap)` with `myseq.replace(gap, "")` to address the deprecation.

#### Reproducible Steps:
1. Obtain the FASTA sequence for the PduK protein reference B1VB70 from UniProt.
2. Use Biopython to read the sequence and perform a sequence operation that involves the deprecated `ungap()` method, e.g., `myseq.ungap("-")`.
3. Observe the BiopythonDeprecationWarning generated.

#### Current Output:
The correct output is generated with the warning.

#### Expected Output:
No warning should be generated, and the code should execute without issues

**Comment by widdowquinn** [comment]
Thanks @monserrj 

This is now fixed with b139660
