### ISSUE TITLE
Not identifying CDS feature despite feature existing

### ISSUE THREAD

**Issue by tharis** [widdowquinn/ncfp#46]
#### Summary:
Please provide a short summary of the issue (just a couple of sentences).
Although there is a match with genbank and the inforamtion is there, ncfp doesn't manage to find the CDS using the Gn field.

#### Description:
Please describe the issue as clearly as possible, taking as much space as you need.
Uniprot header sequence matches genbank entry, tries extracting CDS with locus tag which fails, then tries with GN field which doesn't find a match. When searching manually on ncbi page there is a match however. 
I remember you doing some investigating and found that at a certain step, ncfp deletes a motif from the beginning of the header so the query can be taken forward. When this error occurs I think it was because there were two motifs so only the first was deleted and the query could not be taken forward.

#### Reproducible Steps:
Please report steps we can take to reproduce the issue. If it's not possible to reproduce
the issue, please include a description of how you discovered the issue.

I will attach a file to reproduce the error with a sequence that works and one that give the error.

the command i used was

ncfp --unify_seqid -v -s -l file.log in.fasta out.out email@ac.uk -d caches/new_ncfp -c ncfp_cache

If you have a reproducible example (with data if needed/possible), please include it.

Included

#### Current Output:
The current output showing the error. It is helpful to understand the current behaviour.

[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Sequence sp|Q9BLG4|AMT1_DICDI/128-148 matches GenBank entry AF510716.1
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Extracting CDS by locus tag with AA query ID: ('DDB_G0277503',)
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Did not find feature with locus tag ('DDB_G0277503',), trying GN field
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Searching for CDS: amtA
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Could not identify CDS feature for sp|Q9BLG4|AMT1_DICDI/128-148

#### Expected Output:
Describe what you expected the output to be. Knowing the correct behaviour is also very useful.

INFO] [ncbi_cds_from_protein.scripts.ncfp]: Sequence tr|Q22947|Q22947_CAEEL/118-137 matches GenBank entry BX284605.5
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Extracting CDS by locus tag with AA query ID: ('CELE_F08F3.3 F08F3.3',)
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Did not find feature with locus tag ('CELE_F08F3.3 F08F3.3',), trying GN field
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Searching for CDS: rhr-1
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: 	Sequence tr|Q22947|Q22947_CAEEL/118-137 matches CDS feature CCD65593.1
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: 	Extracting coding sequence...
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: 		Translated sequence matches input sequence

#### `ncfp` Version:
0.2.1a1
[example.txt](https://github.com/widdowquinn/ncfp/files/15188386/example.txt)

#### Python Version:
3.9.18

#### Operating System:
Mac

[example.txt](https://github.com/widdowquinn/ncfp/files/15188390/example.txt)

**Comment by widdowquinn** [comment]
I can confirm that I'm also seeing a failure to resolve the sequence:

```text
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Sequence sp|Q9BLG4|AMT1_DICDI/128-148 matches GenBank entry AF510716.1
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Extracting CDS by locus tag with AA query ID: ('DDB_G0277503',)
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Did not find feature with locus tag ('DDB_G0277503',), trying GN field
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Searching for CDS: amtA
[INFO] [ncbi_cds_from_protein.scripts.ncfp]: Could not identify CDS feature for sp|Q9BLG4|AMT1_DICDI/128-148
```

**Comment by widdowquinn** [comment]
Some notes for info:

- The problem sequence has header:

`>sp|Q9BLG4|AMT1_DICDI/128-148 Ammonium transporter 1 OS=Dictyostelium discoideum OX=44689 GN=amtA PE=1 SV=1 Q9BLG4_Helix_3`

- The problem sequence match is [AF510716.1](https://www.ncbi.nlm.nih.gov/nuccore/AF510716.1)

```text
     CDS             37..1428
                     /note="AmtA"
                     /codon_start=1
                     /product="ammonium transport protein A"
                     /protein_id="AAP47145.1"
                     /translation="MVAGEIIKGVAAEITNGSSSSVVQKYLDCANQVAPDPGNTTWVL
                     LSTILVLGMMPALAFFEAGLLRSKNTLSIITQIMSGIVVLTVMWQAFGYSLTFGPDQK
                     GIIGNLDHAFLINVSYDDCSPNAPNIPAAAYAFFMMMFANITPLLMTGAFAERVKFKA
                     FIALTVAWEIIVFYPVAHWIWGGGWLHKYFGVLDFAGGIVIHTSAGVSALVIALYVGR
                     RKDFEKYGGEFPPSNLPLATIGAALLWMGWFGFNAGSALAAGNIATSAVASTQIGGSF
                     SAIVWIILSAAKGKPNTVSVINGVIAGLAGITPASGYINSQYSIGLGICLGLASYYSV
                     VLLKHKLHIDDALDVSSVHGLTGIIGSLAIGFCAELSVNPNGANGAFYGNPKLIGTQL
                     LGVVSVAVWAAAWTWVLLKIIDATIGVKIDESEEELGLDLVEHGEFAYHNISLQGNEN
                     HYSSVINSHDFFK"
```

- The sequence that matches has header

`>tr|Q22947|Q22947_CAEEL/118-137 Ammonium transporter AmtB-like domain-containing protein OS=Caenorhabditis elegans OX=6239 GN=rhr-1 PE=1 SV=1 Q22947_Helix_3`

- The match is (in [GCF_000002985.6_WBcel235](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/002/985/GCF_000002985.6_WBcel235/GCF_000002985.6_WBcel235_genomic.gbff.gz)):

```text
     CDS             join(5428217..5428270,5428564..5429010,5429059..5429355,
                     5429554..5429840,5429889..5430129,5430181..5430246)
                     /gene="rhr-1"
                     /locus_tag="CELE_F08F3.3"
                     /standard_name="F08F3.3"
                     /note="Confirmed by transcript evidence"
                     /codon_start=1
                     /product="Ammonium transporter AmtB-like domain-containing
                     protein"
                     /protein_id="NP_001370490.1"
                     /db_xref="EnsemblGenomes-Gn:WBGene00004358"
                     /db_xref="GeneID:178927"
                     /db_xref="GOA:Q22947"
                     /db_xref="InterPro:IPR002229"
                     /db_xref="InterPro:IPR024041"
                     /db_xref="InterPro:IPR029020"
                     /db_xref="UniProtKB/TrEMBL:Q22947"
                     /db_xref="WormBase:WBGene00004358"
                     /translation="MRSPLHQNQLTLILGLFQVVFLVIFALYGSYDASALPSETKNVE
                     EAARMTNLYPLFQDTHVMIFIGFGFLMTFLKRYGFSAVSINMLLAVFTIQWGIIVRGM
                     ASAHHGFKFTISLEQLLTADFAAAVILISMGAMLGKLSPSQYVIMAFFETPVALIVEH
                     ICVHNLQINDVGGSIIVHAFGAYFGLACAKGFGKKEQRGHTNEGSTYHTDIFAMIGAI
                     FLWIYWPSFNAAVAATDDARQRAVANTFLSLCACTMTTFLVSQAVDKHKRFDMVHIAN
                     STLAGGVAIGTTANVVLEPYHAMIIGVIAGAVSVIGYKYITPFLSEKLGIHDTCGVNN
                     LHGMPGLIAGFASIAFLFIYDETRYPAQYDKIYPGMARGEDRTRMFDEKTQALNQLMA
                     IGLVFLASTVSGYLTGLLLKLKIWDQVRDDEYYADGDYFETPGDYDFTSRIVTSVKQI
                     EVAEYNPLSQKEV"
```

**Comment by widdowquinn** [comment]
With reference to the info above, the problem we have for identification is that, for the matching pair, the `\gene` field in the `CDS` is what matches the `GN` field. We can identify the corresponding CDS using this gene name.

For the non-matching pair though, there are no identifiers in common between the query sequence header and a _controlled_ field in the CDS record. The `\note` field can contain any free text and is not required to specify any particular data - so we should not rely on it for matching.

However, record [AF510716.1](https://www.ncbi.nlm.nih.gov/nuccore/AF510716.1) suggests another way forward: if there is one and only one CDS regions indicated, we can proceed as if this is going to be a candidate coding sequence. We can try to extract the sequence as usual, and make the normal checks (translate the indicated coding region and check it matches the query sequence).
